import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header>
                    <nav className="text-md flex w-full transform justify-between p-1 py-2 duration-300 text-slate-50">
                        <Link href="/">handlelista.no</Link>
                    </nav>
                </header>
                {children}
            </body>
        </html>
    );
}
